### ISSUE TITLE
Make macros more idiomatic.

### ISSUE THREAD

**Issue by marcioAlmada** [preprocess/pre-class-accessors#1]
There is no guide on how to make good macros yet, but here is how one can achieve a combination of optional structures - like you did with some N x N macro permutation on your property accessor macro.

I just added this test as a guide: [property_accessors.phpt](https://github.com/marcioAlmada/yay/blob/7e3abbe5459715bb1695cb54f2b70772b9cc5e77/tests/phpt/property_accessors.phpt)

Inlined example:

```php
<?php
macro {
    private T_VARIABLE·variable {
        ·repeat
        (
            ·either
            (
                ·chain
                (
                    get,
                    ·optional(·chain(·token(':'), ·ns()·_))·getter_return_type,
                    ·between(·token('{'), ·layer(), ·token('}'))·getter_body
                )
                ·getter
                ,
                ·chain
                (
                    set,
                    ·token('('),
                    ·layer()·setter_args,
                    ·token(')'),
                    ·optional(·chain(·token(':'), ·ns()·_))·setter_return_type,
                    ·between(·token('{'), ·layer(), ·token('}'))·setter_body
                )
                ·setter
            )
        )
        ·accessors
    };
} >> {
    private T_VARIABLE·variable;
    ·accessors ··· {
        ·setter ?··· {
            private function ··concat(__set_ ··unvar(T_VARIABLE·variable))(·setter_args) ·setter_return_type {
                ·setter_body
            }
        }
        ·getter ?··· {
            private function ··concat(__get_ ··unvar(T_VARIABLE·variable))() ·getter_return_type {
                ·getter_body
            }
        }
    }
}
```

1. It takes care of variable ordering of getter, setter.
2. You can add other types of accessors without producing N x N macros
3. I took the liberty to rework the setter feature in order so there is no hidden `$value` variable
4. No need to use `·unsafe` unless the expansion is really intentionally outputting something that could clash with the scope, like a literal `$var` or `goto` label.

**Comment by assertchris** [comment]
I absolutely love this idiomatic syntax. To be honest, I understand very little of how the Yay syntax works, so what probably took you minutes to figure out and express would have taken me far longer. I've replaced the previous macros with a modified version of this new macro.

I'm going to stay away from the type hints, for now. I'd far rather pair them with a type hint on the property (like `private string $name`), and generally prefer succinct code over typed code, in these macros. That's not to say your version is bad - just something different from what I had in mind...

Thank you for all the hard work you've put into Yay, by the way! :)
